### PR TITLE
add support for equipment

### PR DESCRIPTION
**Pull request by goatchita**
Added support for items under the Equipment category on the RealmEye Wiki. Haven't completely tested it yet, will do it later.

Edit: Just a note, but in the future I'll avoid developing directly on the main repo and instead stick to forking.

### CODE REVIEW

**Comment by 4ndrewC** [comment]
Equipment name under a character is different from the name on it's page
eg.
Character's ring: Ring of Unbound Health T6
Page name: Ring of Unbound Health
    - As a result, sprite_urls, projectile_urls, and desription are all set to None while parsing a character's items

Consider parsing the tier of the equipment and adding that as another variable under Equipment class

Strings seem to work, 's work for both item page and items under characters

**Review by 4ndrewC — COMMENTED** [review]
Equipment name under a character is different from the name on it's page
eg.
Character's ring: Ring of Unbound Health T6
Page name: Ring of Unbound Health
- As a result, sprite_urls, projectile_urls, and desription are all set to None while parsing a character's items

Consider parsing the tier of the equipment and adding that as another variable under Equipment class

Strings seem to work, 's work for both item page and items under characters

**Comment by thedrdu** [comment]
> As a result, sprite_urls, projectile_urls, and desription are all set to None while parsing a character's items

Well, the actual reason this happens is because it would take an additional http request to retrieve that information. On a page with characters, you don't have direct access to the equipment information, except the given name and sprite url(I haven't found a way to get that yet). But since there exist shiny variants of sprites, I'm not sure if it would be good practice to have partial Equipment objects that are missing some variants of the sprite. Would love to hear your thoughts on this.

> Consider parsing the tier of the equipment and adding that as another variable under Equipment class

After some searching on the wiki, it seems like the tier is a consistent attribute across all equipment. Will add support for that. Is the tier guaranteed to be part of the equipment name when outside of the equipment's wiki page? I'm pretty sure, but I'd like some additional investigation/confirmation.

**Comment by 4ndrewC** [comment]
> > Is the tier guaranteed to be part of the equipment name when outside of the equipment's wiki page?
Seems that way for trading page and character equipments. But for specific trade offer pages, I can't find anything in the HTML referring to the item (name, link, img url, etc). However, I found this:

<span class="item" data-item="2990" style="background-position: -13064px -184px;" data-original-title="" title=""></span>

This is the element for a deca buy offer on one of the trade offer pages. data-item="2990" seems to be a consistent attribute specific to deca across all trade offer pages

**Comment by thedrdu** [comment]
> Seems that way for trading page and character equipments.

Got it, I'll go add support for equipment tiers in a bit.


> "span class="item" data-item="2990" style="background-position: -13064px -184px;" data-original-title="" title=""></span"

Wow, that is annoying lol. Maybe we can just not count the stuff on the trading page as the `Equipment` type? I was thinking to have wholly separate models for trading anyway, since it uses that whole ID system.

**Comment by thedrdu** [comment]
We could also possibly just have different models entirely for stuff on a character / stuff on the wiki / stuff on trading

**Comment by 4ndrewC** [comment]
Okay just return character equipment as strings for now and call get_equipement_data() later when needed

**Comment by thedrdu** [comment]
Should tier remain as type `str`? I know we have to handle UT, UT (Limited), ST, etc. but I'm wondering if we can/should use enums instead. Thoughts appreciated–gonna stick with `str` for the time being, though.

**Comment by 4ndrewC** [comment]
> Should tier remain as type `str`? I know we have to handle UT, UT (Limited), ST, etc. but I'm wondering if we can/should use enums instead. Thoughts appreciated–gonna stick with `str` for the time being, though.

Enums might be useful if you want to sort by tier I think, since I don't think strings work directly (T1-T13/T14 < ST < UT I think ST should be above the numbered tiers, but ST is lexicographically smaller than T1-13). Idk much about enums but it looks like a struct in C, which you can sort with custom comparators.

**Review by 4ndrewC — COMMENTED** [review]
I think this is fine

**Pull request merged**
